Fixed a typo in README.md
algolia/instantsearch-workshop pull request #3
Opened 2017-11-04 21:49 UTC by ellieseoejung

In the context, "then" is more suitable than "than".

2017-11-05 09:28 UTC, Haroenv requested changes
Great change, but you accidentally committed the solution here too. Can you change that?

2017-11-05 09:28 UTC, Haroenv commented on search.js
> +  instantsearch.widgets.searchBox({
could you remove the solution from this commit?

2017-11-05 09:30 UTC, Haroenv commented
You should be able to do `git revert -n ca1921a5f64031e331d1ab092e6c7379ad9de66b`

2017-11-06 07:36 UTC, Haroenv approved these changes

2017-11-06 07:36 UTC, merged

2017-11-06 07:36 UTC, Haroenv commented
Thank you @ellieseoejung 🔥

2017-11-08 02:20 UTC, ellieseoejung commented
Yay! My first big PR :D ❤️

2017-11-08 07:51 UTC, Haroenv commented
looking forward to what else you can PR 😄 👌